# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Make python to exe
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: minecraft-calculator
        path: src/dist/linux
    - name: make release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.githubtoken }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "New Build"
        files: src/dist/linux/*.exe
      
